# Generated by Django 3.0.5 on 2020-04-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='post',
            new_name='job',
        ),
    ]
