# Generated by Django 3.0.5 on 2020-09-11 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManagerPreference',
        ),
    ]
