# Generated by Django 3.0.5 on 2020-04-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerevaluation',
            name='answer_img',
        ),
        migrations.AddField(
            model_name='managerevaluation',
            name='answer_two_img',
            field=models.ImageField(null=True, upload_to='application_pics'),
        ),
    ]
