# Generated by Django 3.0.5 on 2020-08-24 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managerpreferences',
            old_name='business_type',
            new_name='business_preference_order',
        ),
    ]
