# Generated by Django 3.0.5 on 2020-04-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20200417_0514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managerevaluation',
            old_name='answer_one',
            new_name='answer_one_caption_one',
        ),
        migrations.AddField(
            model_name='managerevaluation',
            name='answer_one_caption_three',
            field=models.TextField(default='none', max_length=350),
        ),
        migrations.AddField(
            model_name='managerevaluation',
            name='answer_one_caption_two',
            field=models.TextField(default='none', max_length=350),
        ),
    ]
