# Generated by Django 3.0.5 on 2020-08-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20200824_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerpreferences',
            name='business_preference_order',
        ),
        migrations.AddField(
            model_name='managerpreferences',
            name='business_type',
            field=models.CharField(default='none', max_length=60),
        ),
    ]
