# Generated by Django 3.0.5 on 2020-08-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20200824_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerpreferences',
            name='business_type',
        ),
        migrations.AddField(
            model_name='managerpreferences',
            name='business_list_order',
            field=models.CharField(default='none', max_length=500),
        ),
    ]
