# Generated by Django 3.0.5 on 2020-08-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20200827_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerpreference',
            name='post_per_day',
            field=models.IntegerField(default=0),
        ),
    ]
