# Generated by Django 3.0.5 on 2020-04-18 11:21

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20200418_0829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managerevaluation',
            old_name='answer_three',
            new_name='answer_three_caption',
        ),
        migrations.AddField(
            model_name='managerevaluation',
            name='answer_three_img',
            field=django_resized.forms.ResizedImageField(crop=None, default='default.jpg', force_format=None, keep_meta=True, quality=0, size=[300, 300], upload_to='application_pics'),
        ),
    ]
