# Generated by Django 3.0.5 on 2020-04-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_managerevaluation_evaluation_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerevaluation',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
