# Generated by Django 3.0.5 on 2020-04-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_managerevaluation_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerevaluation',
            name='answer_three_img',
            field=models.ImageField(default='default.jpg', upload_to='application_pics'),
        ),
        migrations.AlterField(
            model_name='managerevaluation',
            name='answer_two_img',
            field=models.ImageField(default='default.jpg', upload_to='application_pics'),
        ),
    ]
