# Generated by Django 3.0.5 on 2020-05-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_auto_20200429_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerevaluation',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
