# Generated by Django 3.0.5 on 2020-04-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200408_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business_description',
            field=models.TextField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='business_name',
            field=models.CharField(default='none', max_length=60, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='business_type',
            field=models.CharField(default='none', max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='none', max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='none', max_length=60, unique=True),
        ),
    ]
