# Generated by Django 3.0.5 on 2020-04-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200408_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='business_description',
            field=models.TextField(default='none', max_length=500),
        ),
    ]
