# Generated by Django 3.0.5 on 2020-04-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200410_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='business_name',
            field=models.CharField(default='none', max_length=60),
        ),
        migrations.AlterField(
            model_name='profile',
            name='business_type',
            field=models.CharField(default='none', max_length=60),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='none', max_length=60),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='none', max_length=60),
        ),
    ]
