# Generated by Django 3.0.5 on 2020-04-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200410_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='business_description',
            field=models.TextField(default='none', max_length=350),
        ),
    ]
