# Generated by Django 3.0.5 on 2020-04-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='busy',
            field=models.BooleanField(default=False),
        ),
    ]
