# Generated by Django 3.0.5 on 2020-05-09 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='job_offers',
        ),
    ]
