# Generated by Django 3.0.5 on 2020-05-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20200509_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_offers',
            field=models.CharField(blank=True, default='none', max_length=2000),
        ),
    ]
