# Generated by Django 3.0.5 on 2020-04-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_jobpost_manager_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='service_description',
            field=models.CharField(default='none', max_length=5000),
        ),
    ]
