# Generated by Django 3.0.5 on 2020-05-11 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_jobpost_job_offers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='job_offers',
        ),
    ]
