# Generated by Django 3.0.5 on 2020-05-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_remove_jobpost_job_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_offers',
            field=models.CharField(blank=True, default='none', max_length=5000),
        ),
    ]
