# Generated by Django 3.0.5 on 2020-04-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20200419_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='deadline',
            field=models.DateTimeField(auto_now=True, verbose_name='deadline'),
        ),
    ]
