# Generated by Django 3.0.5 on 2020-05-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_jobpost_job_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='client_viewed_chat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='manager_viewed_chat',
            field=models.BooleanField(default=True),
        ),
    ]
