# Generated by Django 3.0.5 on 2020-04-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_jobpost_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='deadline',
            field=models.DateTimeField(verbose_name='deadline'),
        ),
    ]
