# Generated by Django 3.0.5 on 2020-05-11 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20200511_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='client_viewed_chat',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='manager_viewed_chat',
        ),
    ]
