# Generated by Django 3.0.5 on 2020-05-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20200511_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
