# Generated by Django 3.0.5 on 2020-05-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_jobpost_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='auto_renewal',
            field=models.BooleanField(default=False),
        ),
    ]
