# Generated by Django 3.0.5 on 2020-04-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20200425_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='deadline',
            field=models.DateTimeField(auto_now_add=True, verbose_name='deadline'),
        ),
    ]
