# Generated by Django 3.0.5 on 2020-04-27 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_auto_20200426_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestoneOne', models.BooleanField(default=False)),
                ('milestoneTwo', models.BooleanField(default=False)),
                ('milestoneThree', models.BooleanField(default=False)),
                ('milestoneFour', models.BooleanField(default=False)),
                ('milestoneFile', models.FileField(upload_to='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.JobPost')),
            ],
        ),
    ]
