# Generated by Django 3.0.5 on 2020-04-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_milestonefiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='manager_paid',
            field=models.BooleanField(default=False),
        ),
    ]
