# Generated by Django 3.0.5 on 2020-05-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_jobpost_manager_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
