# Generated by Django 3.0.5 on 2020-05-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_jobpost_job_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='milestone_four_files',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='milestone_one_files',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='milestone_three_files',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='milestone_two_files',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='milestone_four_completed_job_goal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='milestone_one_completed_job_goal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='milestone_three_completed_job_goal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='milestone_two_completed_job_goal',
            field=models.BooleanField(default=False),
        ),
    ]
