# Generated by Django 3.0.5 on 2020-05-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_auto_20200505_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='milestone_four_rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='milestone_one_rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='milestone_three_rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='milestone_two_rated',
            field=models.BooleanField(default=False),
        ),
    ]
