# Generated by Django 3.0.5 on 2020-05-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_auto_20200505_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='milestone_four_rated',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='milestone_one_rated',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='milestone_three_rated',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='milestone_two_rated',
            field=models.IntegerField(blank=True),
        ),
    ]
