# Generated by Django 3.0.5 on 2020-05-07 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_jobpost_client_job_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='milestone_four_rated',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='milestone_one_rated',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='milestone_three_rated',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='milestone_two_rated',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_number', models.IntegerField(default=0)),
                ('milestone_four_statement', models.CharField(default='none', max_length=1000)),
                ('milestone_post_goal_completed', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.JobPost')),
            ],
        ),
    ]
