# Generated by Django 3.0.5 on 2020-05-07 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_auto_20200507_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milestone',
            old_name='milestone_four_statement',
            new_name='milestone_statement',
        ),
    ]
