# Generated by Django 3.0.5 on 2020-05-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_auto_20200507_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='milestone_rating',
            field=models.IntegerField(default=0),
        ),
    ]
