# Generated by Django 3.0.5 on 2020-05-08 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_milestone_milestone_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='completed_milestone_four',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='completed_milestone_one',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='completed_milestone_three',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='completed_milestone_two',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='milestone_four_completed_job_goal',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='milestone_four_rated',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='milestone_four_statement',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='milestone_one_completed_job_goal',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='milestone_one_rated',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='milestone_one_statement',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='milestone_three_completed_job_goal',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='milestone_three_rated',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='milestone_three_statement',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='milestone_two_completed_job_goal',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='milestone_two_rated',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='milestone_two_statement',
        ),
    ]
