# Generated by Django 3.0.5 on 2020-05-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_auto_20200508_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
