# Generated by Django 3.0.5 on 2020-05-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0025_jobpost_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
