# Generated by Django 3.0.5 on 2020-05-09 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0026_milestone_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='deadline',
            field=models.DateTimeField(blank=True, max_length=8, null=True),
        ),
    ]
