# Generated by Django 3.0.5 on 2020-05-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0028_jobpost_job_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_offers',
            field=models.CharField(blank=True, default='none', max_length=2000),
        ),
    ]
