# Generated by Django 3.0.5 on 2020-04-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20200417_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managerevaluation',
            old_name='answer_two',
            new_name='answer_two_caption',
        ),
        migrations.AddField(
            model_name='managerevaluation',
            name='answer_two_what_are_problems',
            field=models.TextField(default='none', max_length=350),
        ),
    ]
