# Generated by Django 3.0.5 on 2020-04-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20200417_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerevaluation',
            name='answer_two_img',
            field=models.ImageField(default='default.jpg', null=True, upload_to='application_pics'),
        ),
    ]
