# Generated by Django 3.0.5 on 2020-04-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20200418_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerevaluation',
            name='answer_one_caption_one',
            field=models.TextField(default='none', max_length=2200),
        ),
        migrations.AlterField(
            model_name='managerevaluation',
            name='answer_one_caption_three',
            field=models.TextField(default='none', max_length=2200),
        ),
        migrations.AlterField(
            model_name='managerevaluation',
            name='answer_one_caption_two',
            field=models.TextField(default='none', max_length=2200),
        ),
        migrations.AlterField(
            model_name='managerevaluation',
            name='answer_two_caption',
            field=models.TextField(default='none', max_length=2200),
        ),
        migrations.AlterField(
            model_name='managerevaluation',
            name='answer_two_img',
            field=models.ImageField(default='default.jpg', upload_to='application_pics'),
        ),
        migrations.AlterField(
            model_name='managerevaluation',
            name='answer_two_what_are_problems',
            field=models.TextField(default='none', max_length=2200),
        ),
    ]
