# Generated by Django 3.0.5 on 2020-04-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20200418_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerevaluation',
            name='answer_three_caption',
            field=models.TextField(default='none', max_length=2200),
        ),
    ]
