# Generated by Django 3.0.5 on 2020-04-16 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_post', models.IntegerField()),
                ('length', models.IntegerField()),
                ('price_paid', models.FloatField(null=True)),
                ('paid_for', models.IntegerField(default=False)),
                ('job_complete', models.BooleanField(default=False)),
                ('captions', models.BooleanField(default=False)),
                ('search_for_content', models.BooleanField(default=False)),
                ('post_for_you', models.BooleanField(default=False)),
                ('engagement', models.BooleanField(default=False)),
                ('service_description', models.CharField(default='none', max_length=1000)),
                ('manager_randomly_assigned', models.BooleanField(default=True)),
                ('instagram', models.BooleanField(default=False)),
                ('facebook', models.BooleanField(default=False)),
                ('instagram_username', models.CharField(blank=True, default='none', max_length=100)),
                ('facebook_username', models.CharField(blank=True, default='none', max_length=100)),
                ('completed_milestone_one', models.BooleanField(default=False)),
                ('milestone_one_statement', models.CharField(default='none', max_length=1000)),
                ('completed_milestone_two', models.BooleanField(default=False)),
                ('milestone_two_statement', models.CharField(default='none', max_length=1000)),
                ('completed_milestone_three', models.BooleanField(default=False)),
                ('milestone_three_statement', models.CharField(default='none', max_length=1000)),
                ('completed_milestone_four', models.BooleanField(default=False)),
                ('milestone_four_statement', models.CharField(default='none', max_length=1000)),
                ('date_requested', models.DateTimeField(auto_now_add=True, verbose_name='date requested')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
