# Generated by Django 3.0.5 on 2020-04-12 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_post', models.IntegerField(max_length=56)),
                ('length', models.IntegerField()),
                ('pricePaid', models.IntegerField(null=True)),
                ('job_complete', models.BooleanField(default=False)),
                ('captions', models.BooleanField(default=False)),
                ('search_for_content', models.BooleanField(default=False)),
                ('instagram', models.BooleanField(default=False)),
                ('Facebook', models.BooleanField(default=False)),
                ('date_requested', models.DateTimeField(auto_now_add=True, verbose_name='date requested')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
