# Generated by Django 3.0.5 on 2020-04-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='manager_payment',
            field=models.FloatField(null=True),
        ),
    ]
