# Generated by Django 3.0.5 on 2020-04-12 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20200412_0542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='pricePaid',
            new_name='price_paid',
        ),
    ]
