# Generated by Django 3.0.5 on 2020-04-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20200412_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='completed_milestone_four',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='completed_milestone_one',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='completed_milestone_three',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='completed_milestone_two',
            field=models.BooleanField(default=False),
        ),
    ]
