# Generated by Django 3.0.5 on 2020-04-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20200412_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='milestone_four_description',
            field=models.CharField(default='none', max_length=1000),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='milestone_one_description',
            field=models.CharField(default='none', max_length=1000),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='milestone_three_description',
            field=models.CharField(default='none', max_length=1000),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='milestone_two_description',
            field=models.CharField(default='none', max_length=1000),
        ),
    ]
