# Generated by Django 3.0.5 on 2020-04-12 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20200412_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='milestone_four_description',
            new_name='milestone_four_statement',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='milestone_one_description',
            new_name='milestone_one_statement',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='milestone_three_description',
            new_name='milestone_three_statement',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='milestone_two_description',
            new_name='milestone_two_statement',
        ),
    ]
