# Generated by Django 3.0.5 on 2020-04-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20200419_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
