# Generated by Django 3.0.5 on 2020-04-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20200412_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='milestone_four_statement',
            field=models.CharField(default='none', max_length=1000),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='milestone_one_statement',
            field=models.CharField(default='none', max_length=1000),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='milestone_three_statement',
            field=models.CharField(default='none', max_length=1000),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='milestone_two_statement',
            field=models.CharField(default='none', max_length=1000),
        ),
    ]
