# Generated by Django 3.0.5 on 2020-04-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20200412_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='instagram_username',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
