# Generated by Django 3.0.5 on 2020-04-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_jobpost_instagram_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='facebook_username',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='service_description',
            field=models.CharField(default='none', max_length=1000),
        ),
    ]
