# Generated by Django 3.0.5 on 2020-04-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20200426_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='deadline',
            field=models.DateTimeField(blank=True, max_length=8, null=True),
        ),
    ]
