# Generated by Django 3.0.5 on 2020-04-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20200413_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='facebook_username',
            field=models.CharField(blank=True, default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='instagram_username',
            field=models.CharField(blank=True, default='none', max_length=100),
        ),
    ]
