# Generated by Django 3.0.5 on 2020-04-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_auto_20200426_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_preparation_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_preparation_deadline',
            field=models.DateTimeField(blank=True, max_length=8, null=True),
        ),
    ]
