# Generated by Django 3.0.5 on 2020-04-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_auto_20200414_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='paid_for',
            field=models.IntegerField(default=False),
        ),
    ]
