# Generated by Django 3.0.5 on 2020-04-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_jobpost_paid_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='post_for_you',
            field=models.BooleanField(default=False),
        ),
    ]
