# Generated by Django 3.0.5 on 2020-04-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_jobpost_post_for_you'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='engagement',
            field=models.BooleanField(default=False),
        ),
    ]
