# Generated by Django 3.0.5 on 2020-04-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_jobpost_engagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='manager_randomly_assigned',
            field=models.BooleanField(default=True),
        ),
    ]
