# Generated by Django 3.0.5 on 2020-04-16 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_jobpost_manager_randomly_assigned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='Facebook',
            new_name='facebook',
        ),
    ]
