# Generated by Django 3.0.5 on 2020-04-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_auto_20200416_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='price_paid',
            field=models.FloatField(null=True),
        ),
    ]
